#!/bin/bash

# Global POST-APPLY script.
# This is a bash script. Tuzk will run this script after the every generator
# has been applied. Tuzk will also create temporary global theme variables
# for you to use for the lifetime of the script.
