#!/bin/bash

# Global PRE-APPLY script.
# This is a bash script. Tuzk will run this script before every generator
# has been applied. Tuzk will also create temporary global theme variables
# for you to use for the lifetime of the script.
