#!/bin/bash

# PRE-APPLY script for sublExternalTheme.
# This is a bash script. Tuzk will run this script before the sublExternalTheme generator
# is applied. Tuzk will also create temporary global theme variables for you to
# use for the lifetime of the script.

SCHEME="$(tuzk --current)"
BG="$(tuzk -r bg)"
FG="$(tuzk -r fg)"
RED="$(tuzk -r red)"
GREY="$(tuzk -r grey)"
PURPLE="$(tuzk -r purple)"
YELLOW="$(tuzk -r yellow)"
FG_DARK="$(tuzk -r fg-dark)"
CONTRAST="$(tuzk -r contrast)"
GREY_DARK="$(tuzk -r grey-dark)"
GREY_BRIGHT="$(tuzk -r grey-bright)"
ACCENT_COLOR="$(tuzk -r accent-color)"
CONTRAST_DARK="$(tuzk -r contrast-dark)"
CONTRAST_DARKER="$(tuzk -r contrast-darker)"

THEME_DIR=$HOME/.config/sublime-text-3/Packages/User/Themes

if [[ ! -d "$THEME_DIR/$SCHEME/images" ]]; then
    echo "INFO: Applying $SCHEME for the first time. Creating necessary folders and files.."
    mkdir -p "$THEME_DIR/$SCHEME/images"
    mkdir -p "$THEME_DIR/$SCHEME/file_types"
    cp -r "$THEME_DIR/Tuzk/images" "$THEME_DIR/$SCHEME/"
    cp -r "$THEME_DIR/Tuzk/file_types" "$THEME_DIR/$SCHEME/"
    cp -r "$THEME_DIR/Tuzk/icons" "$THEME_DIR/$SCHEME/"
    cp -r "$THEME_DIR/Tuzk/git" "$THEME_DIR/$SCHEME/"

    ## Processing Images
    find "$THEME_DIR/$SCHEME/images" -maxdepth 2 -type f | while read -r FILEPATH; do
        sed -i "s/%%bg%%/$BG/g" $FILEPATH
        sed -i "s/%%grey%%/$GREY/g" $FILEPATH
        sed -i "s/%%grey-dark%%/$GREY_DARK/g" $FILEPATH
        sed -i "s/%%grey-bright%%/$GREY_BRIGHT/g" $FILEPATH
        sed -i "s/%%fg%%/$FG/g" $FILEPATH
        sed -i "s/%%fg-dark%%/$FG_DARK/g" $FILEPATH
        sed -i "s/%%accent%%/$ACCENT_COLOR/g" $FILEPATH
        sed -i "s/%%contrast%%/$CONTRAST/g" $FILEPATH
        sed -i "s/%%contrast-dark%%/$CONTRAST_DARK/g" $FILEPATH
        sed -i "s/%%contrast-darker%%/$CONTRAST_DARKER/g" $FILEPATH

        DIR="$(dirname "${FILEPATH}")"
        FILE="$(basename "${FILEPATH}")"
        SIZE=$(cat $FILEPATH | awk -F ' ' '/viewBox=/{print $3}')
        inkscape -z -e $DIR/$(echo $FILE | cut -f 1 -d '.').png -w $SIZE -h $SIZE $DIR/$FILE
        inkscape -z -e $DIR/$(echo $FILE | cut -f 1 -d '.')@2x.png -w $(($SIZE*2)) -h $(($SIZE*2)) $DIR/$FILE
        inkscape -z -e $DIR/$(echo $FILE | cut -f 1 -d '.')@3x.png -w $(($SIZE*3)) -h $(($SIZE*3)) $DIR/$FILE
        rm -rf $FILEPATH
    done

    ## Processings Widget
    WIDGET="$THEME_DIR/Tuzk/Widget.stTheme"
    WIDGET_SETTINGS="$THEME_DIR/Tuzk/Widget.sublime-settings"
    THEME_WIDGET="$THEME_DIR/$SCHEME/Widget.stTheme"
    THEME_WIDGET_SETTINGS="$THEME_DIR/../Widget.sublime-settings"

    cp -r "$WIDGET" "$THEME_WIDGET"
    sed -i "s/%%grey%%/$GREY/g" "$THEME_WIDGET"
    sed -i "s/%%grey-dark%%/$GREY_DARK/g" "$THEME_WIDGET"
    sed -i "s/%%fg%%/$FG/g" "$THEME_WIDGET"
    sed -i "s/%%red%%/$RED/g" "$THEME_WIDGET"
    sed -i "s/%%purple%%/$PURPLE/g" "$THEME_WIDGET"
    sed -i "s/%%yellow%%/$YELLOW/g" "$THEME_WIDGET"

    cp -r "$WIDGET_SETTINGS" "$THEME_WIDGET_SETTINGS"
    sed -i --follow-symlinks "/color_scheme/c\\\"color_scheme\": \"Packages/User/Themes/$SCHEME/Widget.stTheme\"," "$THEME_WIDGET_SETTINGS"
fi
