#!/bin/bash

# POST-APPLY script for polybar.
# This is a bash script. Tuzk will run this script after the polybar generator
# is applied. Tuzk will also create temporary global theme variables for you to
# use for the lifetime of the script.
