#!/bin/bash

# PRE-APPLY script for rofi.
# This is a bash script. Tuzk will run this script before the rofi generator
# is applied. Tuzk will also create temporary global theme variables for you to
# use for the lifetime of the script.
