#!/bin/bash

# PRE-APPLY script for i3.
# This is a bash script. Tuzk will run this script before the i3 generator
# is applied. Tuzk will also create temporary global theme variables for you to
# use for the lifetime of the script.
